import { defineEventHandler } from 'h3'
import {
  UserRole, UserRoleLabels,
  CustomerStatus, CustomerStatusLabels,
  OpportunityStatus, OpportunityStatusLabels,
  ContractStatus, ContractStatusLabels,
  ProjectStatus, ProjectStatusLabels,
  TaskStatus, TaskStatusLabels,
  TaskPriority, TaskPriorityLabels,
  ProductStatus, ProductStatusLabels,
  CommissionStatus, CommissionStatusLabels,
  FollowUpType, FollowUpTypeLabels,
  PaymentMethod, PaymentMethodLabels,
  AIEmployeeRole, AIEmployeeRoleLabels,
  AIProviderType, AIProviderTypeLabels,
  AIReviewStatus, AIReviewStatusLabels,
  AIRiskLevel, AIRiskLevelLabels,
  TodoPriority, TodoPriorityLabels,
  TodoStatus, TodoStatusLabels,
  ListColor, ListColorLabels,
  TransactionType, TransactionTypeLabels,
  TransactionSourceType, TransactionSourceTypeLabels,
  ReimbursementStatus, ReimbursementStatusLabels,
  InventoryTransactionType, InventoryTransactionTypeLabels,
  InvoiceType, InvoiceTypeLabels,
  InvoiceStatus, InvoiceStatusLabels,
  IMConversationType, IMConversationTypeLabels,
  IMMessageType, IMMessageTypeLabels,
  IMMemberRole, IMMemberRoleLabels,
  RiskType, RiskTypeLabels,
  RiskStatus, RiskStatusLabels,
  ImpactLevel, ImpactLevelLabels,
  DeliverableStatus, DeliverableStatusLabels,
  QuoteStatus, QuoteStatusLabels,
  TimeLogStatus, TimeLogStatusLabels,
  PaymentPlanStatus, PaymentPlanStatusLabels,
  ContractType, ContractTypeLabels,
  ContractTemplateCategory, ContractTemplateCategoryLabels,
  ProjectMemberRole, ProjectMemberRoleLabels,
  ProjectTemplateCategory, ProjectTemplateCategoryLabels,
  CommentTargetType, CommentTargetTypeLabels,
  CommissionRuleBaseType, CommissionRuleBaseTypeLabels,
  CommissionPayoutStatus, CommissionPayoutStatusLabels,
  NotificationType, NotificationTypeLabels,
  UserStatus, UserStatusLabels,
  CodeRuleDatePart, CodeRuleDatePartLabels,
  enumToOptions
} from '#enums'

export default defineEventHandler(() => {
  return {
    code: 0,
    data: {
      userRoles: enumToOptions(UserRole, UserRoleLabels),
      customerStatus: enumToOptions(CustomerStatus, CustomerStatusLabels),
      opportunityStatus: enumToOptions(OpportunityStatus, OpportunityStatusLabels),
      contractStatus: enumToOptions(ContractStatus, ContractStatusLabels),
      projectStatus: enumToOptions(ProjectStatus, ProjectStatusLabels),
      taskStatus: enumToOptions(TaskStatus, TaskStatusLabels),
      taskPriority: enumToOptions(TaskPriority, TaskPriorityLabels),
      productStatus: enumToOptions(ProductStatus, ProductStatusLabels),
      commissionStatus: enumToOptions(CommissionStatus, CommissionStatusLabels),
      followUpType: enumToOptions(FollowUpType, FollowUpTypeLabels),
      paymentMethod: enumToOptions(PaymentMethod, PaymentMethodLabels),
      aiEmployeeRoles: enumToOptions(AIEmployeeRole, AIEmployeeRoleLabels),
      aiProviderTypes: enumToOptions(AIProviderType, AIProviderTypeLabels),
      aiReviewStatus: enumToOptions(AIReviewStatus, AIReviewStatusLabels),
      aiRiskLevels: enumToOptions(AIRiskLevel, AIRiskLevelLabels),
      todoPriority: enumToOptions(TodoPriority, TodoPriorityLabels),
      todoStatus: enumToOptions(TodoStatus, TodoStatusLabels),
      listColor: enumToOptions(ListColor, ListColorLabels),
      transactionType: enumToOptions(TransactionType, TransactionTypeLabels),
      transactionSourceType: enumToOptions(TransactionSourceType, TransactionSourceTypeLabels),
      reimbursementStatus: enumToOptions(ReimbursementStatus, ReimbursementStatusLabels),
      inventoryTransactionType: enumToOptions(InventoryTransactionType, InventoryTransactionTypeLabels),
      invoiceType: enumToOptions(InvoiceType, InvoiceTypeLabels),
      invoiceStatus: enumToOptions(InvoiceStatus, InvoiceStatusLabels),
      imConversationType: enumToOptions(IMConversationType, IMConversationTypeLabels),
      imMessageType: enumToOptions(IMMessageType, IMMessageTypeLabels),
      imMemberRole: enumToOptions(IMMemberRole, IMMemberRoleLabels),
      riskType: enumToOptions(RiskType, RiskTypeLabels),
      riskStatus: enumToOptions(RiskStatus, RiskStatusLabels),
      impactLevel: enumToOptions(ImpactLevel, ImpactLevelLabels),
      deliverableStatus: enumToOptions(DeliverableStatus, DeliverableStatusLabels),
      quoteStatus: enumToOptions(QuoteStatus, QuoteStatusLabels),
      timeLogStatus: enumToOptions(TimeLogStatus, TimeLogStatusLabels),
      paymentPlanStatus: enumToOptions(PaymentPlanStatus, PaymentPlanStatusLabels),
      contractType: enumToOptions(ContractType, ContractTypeLabels),
      contractTemplateCategory: enumToOptions(ContractTemplateCategory, ContractTemplateCategoryLabels),
      projectMemberRole: enumToOptions(ProjectMemberRole, ProjectMemberRoleLabels),
      projectTemplateCategory: enumToOptions(ProjectTemplateCategory, ProjectTemplateCategoryLabels),
      commentTargetType: enumToOptions(CommentTargetType, CommentTargetTypeLabels),
      commissionRuleBaseType: enumToOptions(CommissionRuleBaseType, CommissionRuleBaseTypeLabels),
      commissionPayoutStatus: enumToOptions(CommissionPayoutStatus, CommissionPayoutStatusLabels),
      notificationType: enumToOptions(NotificationType, NotificationTypeLabels),
      userStatus: enumToOptions(UserStatus, UserStatusLabels),
      codeRuleDatePart: enumToOptions(CodeRuleDatePart, CodeRuleDatePartLabels),
    }
  }
})