allowBuilds:
  '@parcel/watcher': false
  '@tailwindcss/oxide': false
  better-sqlite3: true
  esbuild: false
  protobufjs: true
  puppeteer: true
  simple-git-hooks: true
  tesseract.js: true
  unrs-resolver: false
  vue-demi: false
